# Generated by Django 6.0.3 on 2026-04-25 07:18

from django.db import migrations, models


def backfill_member_ids(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    for row in Member.objects.all().order_by("pk"):
        Member.objects.filter(pk=row.pk).update(
            id_number=f"M{int(row.pk):06d}"
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="id_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Set automatically as M + zero-padded primary key (e.g. M000042).",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_member_ids, noop_reverse),
    ]
