# Generated by Django 6.0.3 on 2026-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_split_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment_received_on',
            field=models.DateField(blank=True, help_text='Date payment was received. Can differ from membership start (e.g. pay today, start next week).', null=True),
        ),
    ]
