# Generated by Django 6.0.3 on 2026-04-25 07:50

from django.db import migrations, models


def backfill_paid_from_payment_date(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    Member.objects.filter(payment_received_on__isnull=False).update(
        member_payment_status="paid"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_payment_received_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], db_index=True, default='pending', help_text='Recorded payment status for this membership (enrollment / dues).', max_length=20),
        ),
        migrations.RunPython(backfill_paid_from_payment_date, migrations.RunPython.noop),
    ]
