# Generated by Django 6.0.4 on 2026-04-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_add_member_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(default='Gym Admin', max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('admin_display_name', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank transfer'), ('online', 'Online')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('student', 'Student'), ('family', 'Family'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('desk', 'Front desk'), ('staff', 'Staff'), ('self', 'Self-service')], default='desk', max_length=20)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='members.member')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('renewed', 'Renewed')], default='updated', max_length=20)),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('student', 'Student'), ('family', 'Family'), ('custom', 'Custom')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
