# Generated by Django 6.0.4 on 2026-04-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_gymsetting_payment_due_date_payment_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='custom_plan_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='member',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
