# Generated by Django 6.0.4 on 2026-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_custom_plan_name_member_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Lebanon E.164: +961 and 8 digits, e.g. +96131234567', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20),
        ),
    ]
