# Generated by Django 5.2.1 on 2026-05-01 10:54

import django.utils.timezone
from django.db import migrations, models


def copy_description_to_notes(apps, schema_editor):
    Payment = apps.get_model("members", "Payment")
    for payment in Payment.objects.exclude(description="").only("id", "description"):
        Payment.objects.filter(id=payment.id).update(notes=payment.description)


def map_legacy_methods(apps, schema_editor):
    Payment = apps.get_model("members", "Payment")
    Payment.objects.filter(method="transfer").update(method="bank_transfer")
    Payment.objects.filter(method="online").update(method="other")


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_payment_invoice_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(copy_description_to_notes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('membership', 'Membership payment'), ('registration', 'Registration fee'), ('personal_training', 'Personal training'), ('merchandise', 'Product / merchandise'), ('penalty', 'Penalty / late fee'), ('other', 'Other')], db_index=True, default='membership', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.RunPython(map_legacy_methods, migrations.RunPython.noop),
    ]
