# Generated by Django 5.2.1 on 2026-05-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_payment_description_payment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('purpose', models.CharField(choices=[('membership', 'Membership payment'), ('registration', 'Registration fee'), ('personal_training', 'Personal training'), ('merchandise', 'Product / merchandise'), ('penalty', 'Penalty / late fee'), ('other', 'Other')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'status'], name='members_mem_member__1dbf4a_idx'), models.Index(fields=['member', 'due_date'], name='members_mem_member__4c6601_idx')],
            },
        ),
    ]
