# Generated by Django 5.2.1 on 2026-05-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_membercharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendancecheckin',
            name='members_att_member__aa75e0_idx',
        ),
        migrations.RenameField(
            model_name='attendancecheckin',
            old_name='checked_in_at',
            new_name='check_in_time',
        ),
        migrations.AddField(
            model_name='attendancecheckin',
            name='check_out_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancecheckin',
            name='recorded_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='recorded_attendance_visits',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name='attendancecheckin',
            options={'ordering': ['-check_in_time']},
        ),
        migrations.AddIndex(
            model_name='attendancecheckin',
            index=models.Index(fields=['member', 'check_in_time'], name='members_att_member_ckin_idx'),
        ),
    ]
